/**
 * Downloads the two font families once and writes a self-hosted @font-face
 * stylesheet, so the page stops depending on a render-blocking Google Fonts
 * request (and on a third party at all).
 *
 * Run: node tools/fetch-fonts.mjs
 */
import { writeFile, mkdir, access } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'public', 'fonts');
await mkdir(outDir, { recursive: true });

// Both families are variable fonts, so one file per family covers the whole
// weight range — one request instead of one per weight.
const FAMILIES = [
  { css: 'Syne:wght@600..800', family: 'Syne', range: '600 800', weights: [600, 800] },
  { css: 'Inter:wght@400..700', family: 'Inter', range: '400 700', weights: [400, 700] },
];

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const faces = [];

for (const { css, family, range, weights } of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${css}&display=swap`;
  const cssText = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

  // Each face is preceded by a /* subset */ comment, so match them together.
  const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
  let match;
  while ((match = blockRe.exec(cssText)) !== null) {
    const [, subset, body] = match;

    // latin-ext, cyrillic, greek … we only want plain `latin`.
    if (subset !== 'latin') continue;

    const weight = /font-weight:\s*(\d+)/.exec(body)?.[1];
    const src = /url\((https:[^)]+\.woff2)\)/.exec(body)?.[1];
    if (!weight || !src || !weights.includes(Number(weight))) continue;

    const name = `${family.toLowerCase()}-${weight}.woff2`;
    const bytes = Buffer.from(await (await fetch(src)).arrayBuffer());
    await writeFile(join(outDir, name), bytes);
    faces.push({ family, range, name, bytes: bytes.length });
    console.log(`  ${name.padEnd(20)} ${(bytes.length / 1024).toFixed(1).padStart(6)} KB`);
  }
}

const cssOut = `/* Self-hosted fonts — generated by tools/fetch-fonts.mjs. Do not edit by hand. */
${faces
  .map(
    (f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: \;
  font-display: swap;
  src: url('/fonts/${f.name}') format('woff2');
}`
  )
  .join('\n')}
`;

await writeFile(join(root, 'src', 'styles', 'fonts.css'), cssOut);
console.log(`\nWrote src/styles/fonts.css (${faces.length} faces)`);
